spring.application.name=course-consultation

spring.profiles.default=local

# Ch? ki?m tra c?u trúc b?ng
spring.jpa.hibernate.ddl-auto=validate

# M?c ??nh không in SQL và chi ti?t l?i ra response
spring.jpa.show-sql=false
spring.web.error.include-message=never