server.port=${PORT:8082}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true