--
-- PostgreSQL database dump
--

\restrict BPqrJEKjbAB7FzqfXwDaWfesWg1vxLjRGhyE1iY3g3kUpezIa3c1YA4OQOSc7R0

-- Dumped from database version 17.11 (Debian 17.11-1.pgdg13+2)
-- Dumped by pg_dump version 17.11 (Debian 17.11-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookings (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    course_id bigint NOT NULL,
    slot_id bigint NOT NULL,
    status character varying(20) DEFAULT 'CONFIRMED'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_booking_status CHECK (((status)::text = ANY ((ARRAY['CONFIRMED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying, 'NO_SHOW'::character varying])::text[])))
);


--
-- Name: bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consultants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consultants (
    id bigint NOT NULL,
    full_name character varying(100) NOT NULL,
    expertise character varying(200) NOT NULL,
    bio text,
    active boolean DEFAULT true NOT NULL
);


--
-- Name: consultants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.consultants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consultants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consultation_slots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consultation_slots (
    id bigint NOT NULL,
    consultant_id bigint NOT NULL,
    start_at timestamp without time zone NOT NULL,
    active boolean DEFAULT true NOT NULL,
    CONSTRAINT chk_slot_start CHECK (((EXTRACT(minute FROM start_at) = ANY (ARRAY[(0)::numeric, (30)::numeric])) AND (EXTRACT(second FROM start_at) = (0)::numeric)))
);


--
-- Name: consultation_slots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.consultation_slots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consultation_slots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    description text,
    prerequisites text,
    duration_weeks integer NOT NULL,
    active boolean DEFAULT true NOT NULL,
    CONSTRAINT courses_duration_weeks_check CHECK ((duration_weeks > 0))
);


--
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    full_name character varying(100) NOT NULL,
    email character varying(150) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(20) DEFAULT 'CUSTOMER'::character varying NOT NULL,
    CONSTRAINT chk_user_role CHECK (((role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);


--
-- Name: consultants consultants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consultants
    ADD CONSTRAINT consultants_pkey PRIMARY KEY (id);


--
-- Name: consultation_slots consultation_slots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consultation_slots
    ADD CONSTRAINT consultation_slots_pkey PRIMARY KEY (id);


--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- Name: consultation_slots uq_consultant_start; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consultation_slots
    ADD CONSTRAINT uq_consultant_start UNIQUE (consultant_id, start_at);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: uq_booking_occupied_slot; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_booking_occupied_slot ON public.bookings USING btree (slot_id) WHERE ((status)::text <> 'CANCELLED'::text);


--
-- Name: bookings bookings_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: bookings bookings_slot_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_slot_id_fkey FOREIGN KEY (slot_id) REFERENCES public.consultation_slots(id);


--
-- Name: bookings bookings_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: consultation_slots consultation_slots_consultant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consultation_slots
    ADD CONSTRAINT consultation_slots_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.consultants(id);


--
-- PostgreSQL database dump complete
--

\unrestrict BPqrJEKjbAB7FzqfXwDaWfesWg1vxLjRGhyE1iY3g3kUpezIa3c1YA4OQOSc7R0


-- Consultant applications and approved working schedules.

BEGIN;
SET LOCAL search_path = public;
ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_user_role;
ALTER TABLE users ADD CONSTRAINT chk_user_role CHECK (role IN ('CUSTOMER', 'ADMIN', 'CONSULTANT'));
ALTER TABLE consultants ADD COLUMN IF NOT EXISTS user_id bigint UNIQUE REFERENCES users(id);
ALTER TABLE consultants ADD COLUMN IF NOT EXISTS available_from time;
ALTER TABLE consultants ADD COLUMN IF NOT EXISTS available_until time;

CREATE TABLE IF NOT EXISTS consultant_work_days (
    consultant_id bigint NOT NULL REFERENCES consultants(id),
    day_of_week integer NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    PRIMARY KEY (consultant_id, day_of_week)
);
CREATE TABLE IF NOT EXISTS consultant_courses (
    consultant_id bigint NOT NULL REFERENCES consultants(id),
    course_id bigint NOT NULL REFERENCES courses(id),
    PRIMARY KEY (consultant_id, course_id)
);
CREATE TABLE IF NOT EXISTS consultant_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    phone varchar(20) NOT NULL,
    expertise varchar(200) NOT NULL,
    experience_years integer NOT NULL CHECK (experience_years BETWEEN 0 AND 60),
    bio text NOT NULL,
    portfolio_url varchar(500),
    available_from time NOT NULL,
    available_until time NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    review_note varchar(500),
    reviewed_by bigint REFERENCES users(id),
    created_at timestamp NOT NULL,
    reviewed_at timestamp,
    CHECK (available_until > available_from),
    CHECK (EXTRACT(minute FROM available_from) IN (0,30) AND EXTRACT(second FROM available_from) = 0),
    CHECK (EXTRACT(minute FROM available_until) IN (0,30) AND EXTRACT(second FROM available_until) = 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_pending_consultant_application
    ON consultant_applications(user_id) WHERE status = 'PENDING';
CREATE TABLE IF NOT EXISTS application_work_days (
    application_id bigint NOT NULL REFERENCES consultant_applications(id),
    day_of_week integer NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    PRIMARY KEY (application_id, day_of_week)
);
CREATE TABLE IF NOT EXISTS application_courses (
    application_id bigint NOT NULL REFERENCES consultant_applications(id),
    course_id bigint NOT NULL REFERENCES courses(id),
    PRIMARY KEY (application_id, course_id)
);
COMMIT;
