BEGIN;
SET LOCAL search_path = public;
ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_user_role;
ALTER TABLE users ADD CONSTRAINT chk_user_role CHECK (role IN ('CUSTOMER', 'ADMIN', 'CONSULTANT'));
ALTER TABLE consultants ADD COLUMN IF NOT EXISTS user_id bigint UNIQUE REFERENCES users(id);
ALTER TABLE consultants ADD COLUMN IF NOT EXISTS available_from time;
ALTER TABLE consultants ADD COLUMN IF NOT EXISTS available_until time;

CREATE TABLE IF NOT EXISTS consultant_work_days (
    consultant_id bigint NOT NULL REFERENCES consultants(id),
    day_of_week integer NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    PRIMARY KEY (consultant_id, day_of_week)
);
CREATE TABLE IF NOT EXISTS consultant_courses (
    consultant_id bigint NOT NULL REFERENCES consultants(id),
    course_id bigint NOT NULL REFERENCES courses(id),
    PRIMARY KEY (consultant_id, course_id)
);
CREATE TABLE IF NOT EXISTS consultant_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    phone varchar(20) NOT NULL,
    expertise varchar(200) NOT NULL,
    experience_years integer NOT NULL CHECK (experience_years BETWEEN 0 AND 60),
    bio text NOT NULL,
    portfolio_url varchar(500),
    available_from time NOT NULL,
    available_until time NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    review_note varchar(500),
    reviewed_by bigint REFERENCES users(id),
    created_at timestamp NOT NULL,
    reviewed_at timestamp,
    CHECK (available_until > available_from),
    CHECK (EXTRACT(minute FROM available_from) IN (0,30) AND EXTRACT(second FROM available_from) = 0),
    CHECK (EXTRACT(minute FROM available_until) IN (0,30) AND EXTRACT(second FROM available_until) = 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_pending_consultant_application
    ON consultant_applications(user_id) WHERE status = 'PENDING';
CREATE TABLE IF NOT EXISTS application_work_days (
    application_id bigint NOT NULL REFERENCES consultant_applications(id),
    day_of_week integer NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    PRIMARY KEY (application_id, day_of_week)
);
CREATE TABLE IF NOT EXISTS application_courses (
    application_id bigint NOT NULL REFERENCES consultant_applications(id),
    course_id bigint NOT NULL REFERENCES courses(id),
    PRIMARY KEY (application_id, course_id)
);
COMMIT;
